name: cs7641_ass1

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip=22

  # Code quality control
  - flake8>=4
  - black>=22.0
  - isort>=5.10
  - coverage>=6.4

  # Visualizations
  - matplotlib>=3.5
  - seaborn>=0.11

  # Data & ML libs
  - numpy>=1.22
  - pandas>=1.4, <1.5
  - pandas-profiling>=3.2.0
  - scipy>=1.8
  - scikit-learn>=1.1
  - ipykernel=6.17.1
  - ipython>=7.31, <8.0
  - jupyter>=1.0